version: '2.1'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'db'
      MYSQL_ROOT_PASSWORD: 'db'
    ports:
    - '3306:3306'
    expose:
    - '3306'
    volumes:
    - my-db:/var/lib/mysql
volumes:
  my-db: