INSERT INTO role(id, name, version) VALUES (1, 'CLIENT', 0);
INSERT INTO role(id, name, version) VALUES (2, 'ADMINISTRATOR', 0);
INSERT INTO user_details(id, street, street_number, flat_number, phone_number, city, country, first_name, last_name, version) VALUES (1, 'Polna', '12', '3', '96541', 'Warszawa', 'Polska', 'Jan', 'Testowy', 0);
INSERT INTO user_details(id, street, street_number, flat_number, phone_number, city, country, first_name, last_name, version) VALUES (2, 'Kwiatowa', '32', '51', '1223252', 'Warszawa', 'Polska', 'Zofia', 'Testowa', 0);
INSERT INTO user(id, login, email, password_hash, role_id, user_details_id, version) VALUES (1, 'client', 'client@client.client', '$2a$10$fVVMTviicRYjVnXGIbW7neBtDm5filacjZp6pBVXgAF3zAczmiq8K', 1, 1, 0);
INSERT INTO user(id, login, email, password_hash, role_id, user_details_id, version) VALUES (2, 'admin', 'admin@admin.admin', '$2a$10$fVVMTviicRYjVnXGIbW7neBtDm5filacjZp6pBVXgAF3zAczmiq8K', 2, 2, 0);
INSERT INTO category(id, name, version) VALUES (1, 'fantasy', 0);
INSERT INTO category(id, name, version) VALUES (2, 'przygodowe', 0);
INSERT INTO publisher(id, name, version) VALUES (1, 'Super wydawca', 0);
INSERT INTO book(id, title, author, price, category_id, isbn, number_of_pages, description, publisher_id, version) VALUES (1, 'Ksiazka testowa', 'Jakiś autor', 10.00, 1, 'asdff', 123, 'Bardzo fajna książka', 1, 0);
INSERT INTO book(id, title, author, price, category_id, isbn, number_of_pages, description, publisher_id, version) VALUES (2, 'Kolejna książka', 'Znany autor', 23.50, 2, 'asdfguigiuf', 89, 'Ciekawa książka', 1, 0);
INSERT INTO shipping_method(id, name, price, version) VALUES (1, 'Poczta', 12.50, 0);
INSERT INTO shipping_method(id, name, price, version) VALUES (2, 'Kurier', 18.90, 0);
INSERT INTO payment_status(id, name, version) VALUES (1, 'WAITING_FOR_PAYMENT', 0);
INSERT INTO payment_status(id, name, version) VALUES (2, 'PAID', 0);
INSERT INTO payment_status(id, name, version) VALUES (3, 'CANCELED', 0);
INSERT INTO purchase(id, user_id, payment_status_id, total_price, order_id, shipping_method_id, version) VALUES (1, 1, 1, 46.0, null, 1, 0);
INSERT INTO ordered_book(id, purchase_id, book_id, version) VALUES (1, 1, 1, 0);
INSERT INTO ordered_book(id, purchase_id, book_id, version) VALUES (2, 1, 2, 0);